CODE_MSG_NAME = "0000"
CODE_MSG_CHANNEL = "0100"
CODE_MSG_CONTENT = "1000"
CODE_MSG_CONTENT_LS = "1001"
CODE_MSG_CONTENT_EXIT = "1010"

SERVER_CONNECT_SUCCESS_MSG = "与服务器连接成功"
NEED_NAME_INPUT = "请输入你的昵称:"
NEED_CHANNEL_INPUT = "请输入要聊天的频道名:"

CMD_LIST_USER = ["ls"]
CMD_EXIT = ["exit"]

