# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chatroom_v1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChatRoom(object):
    def setupUi(self, ChatRoom):
        ChatRoom.setObjectName("ChatRoom")
        ChatRoom.resize(785, 595)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ChatRoom.sizePolicy().hasHeightForWidth())
        ChatRoom.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(ChatRoom)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.Online = QtWidgets.QListWidget(self.centralwidget)
        self.Online.setObjectName("Online")
        self.verticalLayout.addWidget(self.Online)
        self.Channel = QtWidgets.QListWidget(self.centralwidget)
        self.Channel.setObjectName("Channel")
        self.verticalLayout.addWidget(self.Channel)
        self.verticalLayout.setStretch(0, 4)
        self.verticalLayout.setStretch(1, 6)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Content = QtWidgets.QListWidget(self.centralwidget)
        self.Content.setAutoFillBackground(False)
        self.Content.setObjectName("Content")
        self.verticalLayout_2.addWidget(self.Content)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Text = QtWidgets.QLineEdit(self.centralwidget)
        self.Text.setMinimumSize(QtCore.QSize(0, 30))
        self.Text.setObjectName("Text")
        self.horizontalLayout.addWidget(self.Text)
        self.Send = QtWidgets.QPushButton(self.centralwidget)
        self.Send.setMinimumSize(QtCore.QSize(0, 30))
        self.Send.setObjectName("Send")
        self.horizontalLayout.addWidget(self.Send)
        self.horizontalLayout.setStretch(0, 6)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 8)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        ChatRoom.setCentralWidget(self.centralwidget)

        self.retranslateUi(ChatRoom)
        QtCore.QMetaObject.connectSlotsByName(ChatRoom)

    def retranslateUi(self, ChatRoom):
        _translate = QtCore.QCoreApplication.translate
        ChatRoom.setWindowTitle(_translate("ChatRoom", "ChatRoom"))
        self.Send.setText(_translate("ChatRoom", "发送"))
